#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "karakeep"
name = "karakeep"
description.en = "Bookmark-everything app (links, notes and images)"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "0.24.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://karakeep.app/"
demo = "https://try.karakeep.app/signin"
admindoc = "https://docs.karakeep.app/Installation/debuntu"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/karakeep-app/karakeep"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]

    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/karakeep-app/karakeep/archive/refs/tags/v0.24.1.tar.gz"
    sha256 = "c252df5a9d8e31d0fa805bef08f7654f13f6d76b590afc8f459ef7380f1862a0"

    [resources.sources.dlp]
    url = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux"
    sha256 = "da18d12e96f56f942706eeae19898edb86fe1880785286d49e66d69e7b55c005"
    insubdir = false
    extract = false
    rename = "yt-dlp"


    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "graphicsmagick, ghostscript, build-essential, software-properties-common, chromium"
