#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install
ynh_hide_warnings corepack enable && corepack prepare pnpm@latest --activate

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

release=$(curl -s https://api.github.com/repos/karakeep-app/karakeep/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }')
secret==$(ynh_string_random --length=36)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

ynh_setup_source --dest_dir="/usr/bin/" --source_id="dlp"
chmod +x "/usr/bin/yt-dlp"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/karakeep.env"

chmod 600 "$install_dir/karakeep.env"
chown "$app:$app" "$install_dir/karakeep.env"

#=================================================
# LOGROTATE
#=================================================
ynh_script_progression "Configuring logrotate to manage application logfiles"

ynh_config_add_logrotate

touch /var/log/$app/${app}-workers.log
touch /var/log/$app/${app}-web.log
touch /var/log/$app/${app}-$app.log

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd --service="${app}-browser" --template="karakeep-browser.service"
ynh_config_add_systemd --service="${app}-web" --template="karakeep-web.service"
ynh_config_add_systemd --service="${app}-workers" --template="karakeep-workers.service"
#ynh_config_add_systemd --service="meilisearch" --template="meilisearch.service"

yunohost service add "${app}-workers" --description="Bookmark-everything app" --log="/var/log/$app/${app}-workers.log"
yunohost service add "${app}-web" --description="Bookmark-everything app" --log="/var/log/$app/${app}-web.log"
yunohost service add "${app}-browser" --description="Bookmark-everything app" --log="/var/log/$app/$app.log"

#yunohost service add "meilisearch" --description="Bookmark-everything app" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL KARAKEEP
#=================================================
ynh_script_progression "Installing the app..."

#pushd "$install_dir"
#	ynh_hide_warnings npm install -g corepack@0.31.0
#popd

pushd "$install_dir/apps/web"
	export NEXT_TELEMETRY_DISABLED=1
	export PUPPETEER_SKIP_DOWNLOAD="true"
	export CI="true"
  	ynh_hide_warnings pnpm install --frozen-lockfile
  	ynh_hide_warnings pnpm build
popd

pushd "$install_dir/apps/workers"
  	ynh_hide_warnings pnpm install --frozen-lockfile
popd

pushd "$install_dir/apps/cli"
  	ynh_hide_warnings pnpm install --frozen-lockfile
  	ynh_hide_warnings pnpm build
popd

pushd "$install_dir/packages/db"
  	ynh_hide_warnings pnpm migrate
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="${app}-workers" --action="start"
ynh_systemctl --service="${app}-web" --action="start"
ynh_systemctl --service="${app}-browser" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
