#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-browser" >/dev/null; then
    yunohost service remove "$app-browser"
fi

if ynh_hide_warnings yunohost service status "$app-web" >/dev/null; then
    yunohost service remove "$app-web"
fi

if ynh_hide_warnings yunohost service status "$app-workers" >/dev/null; then
    yunohost service remove "$app-workers"
fi

#if ynh_hide_warnings yunohost service status "meilisearch" >/dev/null; then
#    yunohost service remove "meilisearch"
#fi

ynh_config_remove_systemd "$app-browser"
ynh_config_remove_systemd "$app-web"
ynh_config_remove_systemd "$app-workers"
#ynh_config_remove_systemd "meilisearch"

ynh_config_remove_nginx

ynh_nodejs_remove

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
